### ISSUE TITLE
Исправление съезжающегося списка

### ISSUE THREAD

**Issue by Ka-ra-siK** [januarydayfin/Clipper#9]
![photo_2024-02-07_12-17-23](https://github.com/januarydayfin/Clipper/assets/53082951/5276ab25-c274-443f-8400-41e6000caa27)

![photo_2024-02-07_12-25-23](https://github.com/januarydayfin/Clipper/assets/53082951/f3e6d5e1-c130-4aff-8153-f164614aa2cc)

При добавлении большого количества слов, список заходит за поле для ввода.
также, при достижении 17 элементов список на экране, что на скрине, не обновляется.
Также, для длинного слова, добавить бы отступы от краев небольшие.
Как предложение: можно добавить еще уведомления, что виджет успешно обновлен)
Samsung Galaxy A12 (API 31)

**Comment by januarydayfin** [comment]
Тост не могу вызвать из контекста виджета к сожалению, хотел сделать так. По списку посмотрю!
